name = "KhepriFrame3DD"
uuid = "1c797e0a-d883-4edd-ad69-3f315fbcf25c"
authors = ["António Menezes Leitão <antonio.menezes.leitao@gmail.com>"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
KhepriBase = "4cc0fe96-1163-46f3-ba32-de1e65d9548f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
ColorTypes = "0.10"
KhepriBase = "0.2"
Reexport = "0.2, 1.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
